// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elqfojdivyyhfrovyuud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscWZvamRpdnl5aGZyb3Z5dXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDc0MTUsImV4cCI6MjA3MjM4MzQxNX0.3v5yQW2O65kFcO-hyRjCkgVDtdBf53EqlbbvA1l2Mpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});